

import FreeCAD
import FreeCADGui

def main():
	selection = FreeCADGui.Selection.getSelection()
	if len(selection) == 0:
		FreeCAD.Console.PrintWarning("Please select an object and then re-run this macro.")
		return

	for model in selection:
		debugBBound(model)

		

def debugBBound(model):

	bbox = model.Shape.BoundBox
	pos = model.Placement.Base
	xlength = str(bbox.XLength)
	ylength = str(bbox.YLength)


	bb_cxp = bbox.XMin + (bbox.XLength/2)
	bb_cyp = bbox.YMin + (bbox.YLength/2)


	dx = bb_cxp - pos.x
	dy = bb_cyp - pos.y

	base_xp = str(pos.x)
	base_yp = str(pos.y)

	#print("BBox:" + model.Label + " > " + str(model.Shape.BoundBox) + " xlen:" + xlength + " ylen:" + ylength + " x:" + xp + " y:" + yp)
	print( model.Label, "bbox:", bbox.XMin, bbox.XMax, bbox.XLength )
	print( model.Label, "calc:", base_xp,">",dx,"/",base_yp,">",dy )

main()